version: '3.8'

services:
  bff:
    build:
      context: ./backend-for-frontend  
    ports:
      - "8000:8000" 
    depends_on:
      - translator
      - language_detector

  language_detector:
    build:
      context: ./language-detector  
    ports:
      - "5001:5001"  

  translator:
    build:
      context: ./translator-as-a-service  
    ports:
      - "5002:5002"  

  
